export const GET_SIMPLE_SEARCH = "GET_SIMPLE_SEARCH";
export const PARSE_SIMPLE_SEARCH = "PARSE_SIMPLE_SEARCH";
export const GET_SIMPLE_SEARCH_LOADED = "GET_SIMPLE_SEARCH_LOADED";

export const GET_FEED = "GET_FEED";
export const FEED_PARSE = "FEED_PARSE";
export const FEED_LOADED = "FEED_LOADED";

export const GET_CHAPTERS = "GET_CHAPTERS";
export const CHAPTERS_LOADED = "CHAPTERS_LOADED";

export const ADD_MANGA_TO_FAVORITES = "ADD_MANGA_TO_FAVORITES";
export const REMOVE_MANGA_FROM_FAVORITES = "REMOVE_MANGA_FROM_FAVORITES";

export const API_ERRORED = "API_ERRORED";