export const GET_SIMPLE_SEARCH = "GET_SIMPLE_SEARCH";
export const PARSE_SIMPLE_SEARCH = "PARSE_SIMPLE_SEARCH";
export const GET_SIMPLE_SEARCH_LOADED = "GET_SIMPLE_SEARCH_LOADED";

export const GET_FEED = "GET_FEED";
export const FEED_PARSE = "FEED_PARSE";
export const FEED_LOADED = "FEED_LOADED";

export const GET_CHAPTERS = "GET_CHAPTERS";
export const CHAPTERS_LOADED = "CHAPTERS_LOADED";

export const GET_TAGS_LIST = "GET_TAGS_LIST";
export const TAGS_LIST_LOADED = "TAGS_LIST_LOADED";
export const TAGS_LIST_PARSED = "TAGS_LIST_PARSED";

export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_CACHE = "POST_LOGIN_CACHE";
export const LOGIN_LOADED = "LOGIN_LOADED";

export const POST_ADD_TO_READ_LIST = "POST_ADD_TO_READ_LIST";
export const ADD_TO_READ_LIST_LOADED = "ADD_TO_READ_LIST_LOADED";

export const API_ERRORED = "API_ERRORED";